services:
  - type: web
    name: shiny-ufpr-cpa
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: shiny run --host 0.0.0.0 --port $PORT app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9